### ISSUE TITLE
Root by default

### ISSUE THREAD

**Issue by infinity12** [agajews/ApricityOS#10]
It seems like after installation root is enabled by default. When I type a command in the terminal 'm not prompted for a user password.

**Comment by agajews** [comment]
We have it that way be default, but if you want to change the config to ask for a password, run "sudo sed -i 's/%wheel ALL=(ALL) NOPASSWD: ALL/%wheel ALL=(ALL) ALL/g' /etc/sudoers.d/g_wheel" (excluding the double quotation marks around the command). What the command is doing is editing the sudo config file stored at /etc/sudoers.d/g_wheel and replacing the string between the first two slashes with the string between the second and third slashes. We will change to having sudo prompt the user for a password by default for the September release.

**Comment by infinity12** [comment]
Thanks for the quick response
