### ISSUE TITLE
Apricity does not credit any of the developers/designers of the icons, themes or artwork it uses

### ISSUE THREAD

**Issue by snwh** [agajews/ApricityOS#11]
This project is using themes, icons and other artwork assets from existing project and doesn't credit back to them. For instance, at least all the symbolic icons in Apricity are copied right out of my Paper icon set, so I don't appreciate the blatant lack of credit.

**Comment by JoshStrobl** [comment]
Not only is it unappreciated, but it is a blatant violation of GPL license agreements, in the case of horst's Arc theme (and likely many more).

@agajews What the fuck man? Pull your shit together. It takes more effort to actually keep licensing OUT of your repo than it does to keep it in.

**Comment by agajews** [comment]
I'm typing out a CREDITS.md as we speak.

**Comment by fabianfroodo** [comment]
many violations of GPL in a "new os" ....

**Comment by snwh** [comment]
C'mon everyone no need to attack.

@agajews thanks, that's literally all I ask (and many projects with their own permissive licensing).

**Comment by JoshStrobl** [comment]
@agajews Please keep in mind that you're still required to provide a copy of the LICENSE, the header of the files be intact, or the source link within the credits :+1:

**Comment by bmeznarsic** [comment]
Numix icons are also GPL'd.

**Comment by snwh** [comment]
My icons, are https://creativecommons.org/licenses/by-sa/4.0/ however.

**Comment by agajews** [comment]
Updated credits with icons, themes, and licenses. Thanks for the notice.

**Comment by snwh** [comment]
Thanks a bunch.

**Comment by danrabbit** [comment]
@agajews as @JoshStrobl indicated, this doesn't seem to be an acceptable solution. GPL requires that the license be distributed in the actual tarball. You need to include the licenses with the source.

**Comment by snwh** [comment]
It's probably best to include copies of each license.

**Comment by agajews** [comment]
Licenses have been incorporated into the apricity-themes and apricity-icons packages as part of the version 0.1.3 release of each in order to reflect the original licenses of each part of each package.
