### ISSUE TITLE
Inside of VirtualBox doesn't possible to install Guest Addons

### ISSUE THREAD

**Issue by berlotto** [agajews/ApricityOS#14]
I'm running ApricityOS inside VirtualBox.
When I try to install guest addons the script show me a message:
"Unable to determine your linux distribution" and not install nothing, make video working only in 640x480

**Comment by agajews** [comment]
The package that you should install from the Pamac graphical package manager (or from its command-line sibling Pacman), is called virtualbox-guest-utils. That should work just fine.

**Comment by berlotto** [comment]
Tks ! Works fine.
