### ISSUE TITLE
Ice icons not working

### ISSUE THREAD

**Issue by giepa** [agajews/ApricityOS#16]
In Ice when I add a new webapp and select a png icon or click on "Use favicon" the icon is not saved and not displayed in the menu's

**Comment by agajews** [comment]
This is a known bug that we're working on. I'm hoping we'll push an update this week.

**Comment by Glanzer** [comment]
Additionally, I am stunned by the amount of icons that are in the Apricity icon-pack. As someone who used to make 'desktop applications' by writing .desktop files by hand, using 
<code>$ chromium --app=http…</code>
…which didn't show the designated Icons at first. Something that was solved after restarting the gnome-shell.

**Comment by agajews** [comment]
Just wanted to let you know that we just pushed the update that fixes favicon functionality. We're working on adding a feature that would suggest an icon from the Apricity Icons theme based on the name of the to-be-created application, but that's not quite ready yet.
