### ISSUE TITLE
Blank screen with screen recorder software

### ISSUE THREAD

**Issue by ghost** [agajews/ApricityOS#162]
Hello,

I've tried a lot of screen recorder software, e.g., simplescreenrecorder, recordmydesktop, voko, screenstudio, kazam,  etc., but all of them have the exact same problem, the video output is _all black_ and the only thing I can see is the mouse cursor.

I've asked some arch linux users and they said they don't experience it with the plain arch linux installation, so this seems to be apricityos specific.

**Comment by lubo08** [comment]
For me simplescreenrecorder under apricity-os cinnamon work OK on DELL XPS 13 9650.

**Comment by ghost** [comment]
I've now switched to Cinnamon and it worked, definitely a desktop environment problem for Birch - Gnome.

**Comment by ghost** [comment]
Re-installed again using the latest `Apricity OS 11.2016 Birch - Gnome, x86_64` iso and tested with screen recorder `vokoscreen`.

It's now working (also previously with cinnamon).
