### ISSUE TITLE
Panel-Icons broken

### ISSUE THREAD

**Issue by jensMF** [agajews/ApricityOS#26]
After an upgrade a some days ago the panel-icons are not showing correctly.
Now it looks like this (the black one is keepass or jitsi):
![apricityos_broken_icons_in_panel](https://cloud.githubusercontent.com/assets/1620034/10594058/56876978-76c9-11e5-9d27-fa5f80cd7284.jpg)

**Comment by agajews** [comment]
This is a slight incompatibility between the latest version of the Topicons extension and the latest version of Gnome. I believe the Topicons developer is working on updating the extension.

**Comment by gogobebe2** [comment]
I had this same problem on ElementaryOS with the paper icon theme after I installed it through http://snwh.org/paper/

**Comment by jensMF** [comment]
It is fixed! Made my day :-)
