### ISSUE TITLE
troubles with updating and installing.

### ISSUE THREAD

**Issue by MMPhillip** [agajews/ApricityOS#29]
I've got the ApricityOS yesterday, and I totally loved it, but I'm experiencing some troubles when:
1- I try to update the programs using the updater
2- I try to install a program with synaptics.

**Comment by agajews** [comment]
What specifically are the issues you're encountering?

**Comment by Finnerale** [comment]
Perhaps this post helps you

http://apricityos.com/forum/discussion/257/after-beta2-installation-unexpected-error-while-i-m-trying-to-get-24-updates#latest

**Comment by MMPhillip** [comment]
It worked, Thanks Finnerale! and thank you agajews too. It was a problem with the keys.
