### ISSUE TITLE
Creating USB Bootable

### ISSUE THREAD

**Issue by gitdovinicius** [agajews/ApricityOS#47]
QString::arg: Argument missing: <b>Origem</b>, arch/boot/intel_ucode.img
QString::arg: Argument missing: <b>Origem</b>, 676 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/intel_ucode.LICENSE
QString::arg: Argument missing: <b>Origem</b>, 7011 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/memtest
QString::arg: Argument missing: <b>Origem</b>, 146 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/memtest.COPYING
QString::arg: Argument missing: <b>Origem</b>, 17 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/archiso.cfg
QString::arg: Argument missing: <b>Origem</b>, 222 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/archiso_head.cfg
QString::arg: Argument missing: <b>Origem</b>, 819 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/archiso_pxe64.cfg
QString::arg: Argument missing: <b>Origem</b>, 1074 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/archiso_pxe_32_inc.cfg
QString::arg: Argument missing: <b>Origem</b>, 118 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/archiso_pxe_both_inc.cfg
QString::arg: Argument missing: <b>Origem</b>, 158 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/archiso_pxe_choose.cfg
QString::arg: Argument missing: <b>Origem</b>, 220 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/archiso_sys64.cfg
QString::arg: Argument missing: <b>Origem</b>, 298 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/archiso_sys_32_inc.cfg
QString::arg: Argument missing: <b>Origem</b>, 118 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/archiso_sys_both_inc.cfg
QString::arg: Argument missing: <b>Origem</b>, 158 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/archiso_sys_choose.cfg
QString::arg: Argument missing: <b>Origem</b>, 220 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/archiso_tail.cfg
QString::arg: Argument missing: <b>Origem</b>, 641 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/cat.c32
QString::arg: Argument missing: <b>Origem</b>, 1596 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/chain.c32
QString::arg: Argument missing: <b>Origem</b>, 24 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/cmd.c32
QString::arg: Argument missing: <b>Origem</b>, 1228 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/cmenu.c32
QString::arg: Argument missing: <b>Origem</b>, 3660 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/config.c32
QString::arg: Argument missing: <b>Origem</b>, 1464 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/cptime.c32
QString::arg: Argument missing: <b>Origem</b>, 4184 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/cpu.c32
QString::arg: Argument missing: <b>Origem</b>, 4480 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/cpuid.c32
QString::arg: Argument missing: <b>Origem</b>, 1748 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/cpuidtest.c32
QString::arg: Argument missing: <b>Origem</b>, 2748 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/debug.c32
QString::arg: Argument missing: <b>Origem</b>, 1568 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/dhcp.c32
QString::arg: Argument missing: <b>Origem</b>, 4040 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/disk.c32
QString::arg: Argument missing: <b>Origem</b>, 1988 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/dmi.c32
QString::arg: Argument missing: <b>Origem</b>, 8660 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/dmitest.c32
QString::arg: Argument missing: <b>Origem</b>, 11 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/elf.c32
QString::arg: Argument missing: <b>Origem</b>, 3232 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/ethersel.c32
QString::arg: Argument missing: <b>Origem</b>, 2716 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/gfxboot.c32
QString::arg: Argument missing: <b>Origem</b>, 10 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/gpxecmd.c32
QString::arg: Argument missing: <b>Origem</b>, 1576 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/hdt/modalias.gz
QString::arg: Argument missing: <b>Origem</b>, 94 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/hdt/pciids.gz
QString::arg: Argument missing: <b>Origem</b>, 227 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/hdt.c32
QString::arg: Argument missing: <b>Origem</b>, 161 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/hexdump.c32
QString::arg: Argument missing: <b>Origem</b>, 3704 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/host.c32
QString::arg: Argument missing: <b>Origem</b>, 1804 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/ifcpu.c32
QString::arg: Argument missing: <b>Origem</b>, 4120 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/ifcpu64.c32
QString::arg: Argument missing: <b>Origem</b>, 1720 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/ifmemdsk.c32
QString::arg: Argument missing: <b>Origem</b>, 4260 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/ifplop.c32
QString::arg: Argument missing: <b>Origem</b>, 1872 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/kbdmap.c32
QString::arg: Argument missing: <b>Origem</b>, 1648 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/kontron_wdt.c32
QString::arg: Argument missing: <b>Origem</b>, 4896 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/ldlinux.c32
QString::arg: Argument missing: <b>Origem</b>, 113 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/lfs.c32
QString::arg: Argument missing: <b>Origem</b>, 5076 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/libcom32.c32
QString::arg: Argument missing: <b>Origem</b>, 178 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/libgpl.c32
QString::arg: Argument missing: <b>Origem</b>, 65 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/liblua.c32
QString::arg: Argument missing: <b>Origem</b>, 99 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/libmenu.c32
QString::arg: Argument missing: <b>Origem</b>, 23 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/libutil.c32
QString::arg: Argument missing: <b>Origem</b>, 23 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/linux.c32
QString::arg: Argument missing: <b>Origem</b>, 4700 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/lpxelinux.0
QString::arg: Argument missing: <b>Origem</b>, 73 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/ls.c32
QString::arg: Argument missing: <b>Origem</b>, 2960 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/lua.c32
QString::arg: Argument missing: <b>Origem</b>, 6820 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/mboot.c32
QString::arg: Argument missing: <b>Origem</b>, 9 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/memdisk
QString::arg: Argument missing: <b>Origem</b>, 25 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/meminfo.c32
QString::arg: Argument missing: <b>Origem</b>, 2452 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/menu.c32
QString::arg: Argument missing: <b>Origem</b>, 25 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/pci.c32
QString::arg: Argument missing: <b>Origem</b>, 3336 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/pcitest.c32
QString::arg: Argument missing: <b>Origem</b>, 3460 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/pmload.c32
QString::arg: Argument missing: <b>Origem</b>, 2956 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/poweroff.c32
QString::arg: Argument missing: <b>Origem</b>, 1640 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/prdhcp.c32
QString::arg: Argument missing: <b>Origem</b>, 3116 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/pwd.c32
QString::arg: Argument missing: <b>Origem</b>, 1476 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/pxechn.c32
QString::arg: Argument missing: <b>Origem</b>, 12 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/reboot.c32
QString::arg: Argument missing: <b>Origem</b>, 1356 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/rosh.c32
QString::arg: Argument missing: <b>Origem</b>, 13 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/sanboot.c32
QString::arg: Argument missing: <b>Origem</b>, 1608 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/sdi.c32
QString::arg: Argument missing: <b>Origem</b>, 3148 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/splash.png
QString::arg: Argument missing: <b>Origem</b>, 11 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/sysdump.c32
QString::arg: Argument missing: <b>Origem</b>, 15 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/syslinux.c32
QString::arg: Argument missing: <b>Origem</b>, 7544 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/syslinux.cfg
QString::arg: Argument missing: <b>Origem</b>, 87 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/vesa.c32
QString::arg: Argument missing: <b>Origem</b>, 3068 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/vesainfo.c32
QString::arg: Argument missing: <b>Origem</b>, 2180 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/vesamenu.c32
QString::arg: Argument missing: <b>Origem</b>, 26 KB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/vpdtest.c32
QString::arg: Argument missing: <b>Origem</b>, 1840 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/whichsys.c32
QString::arg: Argument missing: <b>Origem</b>, 2460 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/syslinux/zzjson.c32
QString::arg: Argument missing: <b>Origem</b>, 3528 B
QString::arg: Argument missing: <b>Origem</b>, arch/boot/x86_64/archiso.img
QString::arg: Argument missing: <b>Origem</b>, 22 MB
QString::arg: Argument missing: <b>Origem</b>, arch/boot/x86_64/vmlinuz
QString::arg: Argument missing: <b>Origem</b>, 4266 KB
QString::arg: Argument missing: <b>Origem</b>, arch/pkglist.x86_64.txt
QString::arg: Argument missing: <b>Origem</b>, 26 KB
QString::arg: Argument missing: <b>Origem</b>, arch/x86_64/airootfs.md5
QString::arg: Argument missing: <b>Origem</b>, 47 B
QString::arg: Argument missing: <b>Origem</b>, arch/x86_64/airootfs.sfs
QString::arg: Argument missing: <b>Origem</b>, 1711 MB

**Comment by agajews** [comment]
What tool did you use to create the bootable USB? What kind of computer do you have? Have you checked to make sure your download isn't corrupted? 

This information will help us suggest a course of action.

**Comment by gitdovinicius** [comment]
I've double-checked my download, but I've found the problem.
At first I though I couldn't be so unlucky, but I am, the problem was three pendrive.
Tomorrow i will try another pendrive and I will post the result.

**Comment by gitdovinicius** [comment]
I tested in a new pendrive and worked
