### ISSUE TITLE
Gnome Shell (?) Crashes When Reducing Number of Workspaces in Tweak Tool

### ISSUE THREAD

**Issue by marytee** [agajews/ApricityOS#48]
I was researching your distro for a review when I encountered a bug. The bug is triggered in both the live and installed environment.  Steps to reproduce:

1. Boot to live environment (or install and boot to desktop).
2. Open tweak tool.
3. Click Workspaces at bottom of panel.
4. Click "-" (minus) to reduce workspace count from 4 to 3.
5. Screen background goes black and any open applications become unstable/freeze.

If any further information is needed, please advise.

**Comment by agajews** [comment]
This is actually a bug with Gnome tweak tool itself. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=782075

**Comment by marytee** [comment]
I did not realize that!  Thanks. (I don't normally use Gnome)
