### ISSUE TITLE
Do not use BTsync

### ISSUE THREAD

**Issue by lunemec** [agajews/ApricityOS#5]
Hello,

I just wanted to share my experience with btsync. I've been using it for 2 years, and was happy, usually. What turned me unhappy however was when I lost large portion of synced data. This happens when you turn on PC with old version of synced folder. The other machines think that this newly turned on pc has newer version and they sync its data to theirs and overwrite newer versions of the data in the process. I tried to solve this by reporting it to BTSync developers, but they said this is known issue and there may never be a way to fix it.

I then switched to Megasync, but I didn't like the proprietary software. Now I'm using **Syncthing** and I'm very happy with it. It works as expected. It sometimes requires some configuration because of NAT's and FW's but usually works out of the box.

**Comment by agajews** [comment]
Thanks for the advice! The other nice thing about syncthing is that it's completely open source. We just might switch for the next release.

**Comment by lunemec** [comment]
And as a bonus, BTsync can be used to amplify DDoS attacks: https://www.usenix.org/system/files/conference/woot15/woot15-paper-adamsky.pdf

**Comment by agajews** [comment]
August Beta is live with Syncthing :)
