### ISSUE TITLE
Wifi card on x220

### ISSUE THREAD

**Issue by voxmystica** [agajews/ApricityOS#52]
I have a Thinkpad x220. The wifi card is an Intel Centrino Wireless-N 1000. The card is detected and it sees the wifi, but it never connects. It works when I boot up Windows. I am, however, able to use wifi through an USB adapter on Apricity.

**Comment by VecchioLeo** [comment]
Try installing this package: iwlwifi
More in general follow the instruction in this page
https://wiki.archlinux.org/index.php/Wireless_network_configuration#iwlwifi

**Comment by voxmystica** [comment]
The iwlwifi package was installed. I fixed the problem by navigating to lib/firmware and deleting the iwlwifi-1000-5.ucode and replacing it with iwlwifi-1000-3.ucode. I am quite new to linux so this was a major victory for me! Thanks for steering me in the right direction.
