### ISSUE TITLE
not-cached install takes +12h

### ISSUE THREAD

**Issue by lunemec** [agajews/ApricityOS#6]
I tried installing apricityOS from uncached installer, but it took 12h+ and still is not finished. Note that I'm sitting on optical fiber connection 100Mbit+ ... What are the mirrors used for apricity? Are you not using default archlinux mirrors, because I'm writing this on my archlinux workstation and all of the installing I do is downloading at 2MB/s... This seems to me like an issue with mirror, or its location...

I was installing it in Prague, Czech Republic.

**Comment by agajews** [comment]
The installer is using the default Arch repositories. However, we're working on a completely different installer that doesn't try to netinstall everything and doesn't need a cache. We're almost done with it, and will hopefully post instructions for how to use the new installer with an old iso within a few days. We will likely post the August Beta early next week.

**Comment by agajews** [comment]
The August Beta is live! The brand new installer should yield much better results.
