### ISSUE TITLE
Lock screen font is cut off from the right

### ISSUE THREAD

**Issue by lunemec** [agajews/ApricityOS#8]
On the lock screen the font displaying current time is cut off by few pixels from the left (each letter) and looks strange ... I'm not sure if this is the case for all gnome's (will have to check) or if the solution would be to simply lower the font size to fix the issue (there are maybe some boxes where the letters must fit).

**Comment by agajews** [comment]
It looks like it's an issue with GNOME and your screen resolution. There are just a few resolutions in a VM that result in the issue you're having, and those issues persist even when GNOME is set to its defaults.

**Comment by agajews** [comment]
I believe this has been fixed in Gnome 3.18.
