### ISSUE TITLE
All desktop display settings are lost when lowering workspace numbers in tweak

### ISSUE THREAD

**Issue by cribbageSTARSHIP** [agajews/ApricityOS#9]
Via tweak, I went to lower the workspace number to 1. screen blinked and I was told to logout. ended up having to reboot. upon return, the gnome set up had been nuked and I was left with the standard gnome setup.

**Comment by agajews** [comment]
Gnome occasionally gets spooked and decides to crash and disable all extensions. You can restore the custom Apricity setup by running 
gsettings set org.gnome.shell enabled-extensions "['user-theme@gnome-shell-extensions.gcampax.github.com', 'alwayszoomworkspaces@jamie.thenicols.net', 'mediaplayer@patapon.info', 'caffeine@patapon.info', 'scroll-workspaces@gfxmonk.net', 'simple-dock@nothing.org', 'suspend-button@laserb', 'topIcons@adel.gadllah@gmail.com', 'places-menu@gnome-shell-extensions.gcampax.github.com', 'drive-menu@gnome-shell-extensions.gcampax.github.com', 'remove-dropdown-arrows@mpdeimos.com', 'Move_Clock@rmy.pobox.com']".

**Comment by cribbageSTARSHIP** [comment]
Alex,

     Is this something done via the tweak tool? If not can you provide a
link by which I can educate myself how to teach others? I will be
installing this to show my family the OS's capabilities so I'd imagine I
may have to work on this in the future and would like to be prepared. Thank
you.

Will

**Comment by agajews** [comment]
The command must be run in terminal. To run it, open terminal, paste it in with ctrl-shift-v, and hit enter. Another thing you can do to reset Apricity to its default configuration is remove the file found at ~/.firstrun.ran. This can be done by opening the file browser application, hitting ctrl-h to show hidden files, right-clicking the file called .firstrun.ran, and selecting "Move to Trash". Afterwords, reboot the computer and everything should look like normal.

**Comment by agajews** [comment]
I believe the this bug has been fixed in Gnome 3.18.
